name: mongo_pool
description: A MongoDB connection pool for Dart. Using this package, your application will open as many database connections as you specify as soon as it runs.

version: 1.5.0
homepage: https://github.com/merterkoc/mongo_pool

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cached_annotation: ^1.7.1
  meta: ^1.17.0
  mongo_dart: ^0.10.5
  very_good_analysis: ^9.0.0

dev_dependencies:
  build_runner: ^2.5.4
  cached: ^1.7.1
  lints: ^6.0.0
  test: ^1.26.3
